### ISSUE TITLE
Could you kindly provide a publicly accessible dump tool, please

### ISSUE THREAD

**Issue by lanting200** [Omn1z/Counter-Strike2-SDK#1]
Will you frequently update this repository? Do you have a dump tool? I find this SDK to be very perfect. The SDK I obtained using another dump tool is not as concise and clear, making it difficult to quickly analyze the structure and functionality I need.

**Comment by Omn1z** [comment]
If CS2 doesn't die in the first week, then probably yes. Maybe I'll upload a dump utility

**Comment by devingDev** [comment]
Can you teach me how you did this?
